import { randomBytes } from "node:crypto";
import { chmod, mkdir, open } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const configDir = path.join(repoRoot, "config");
const secretsPath = path.join(configDir, "manager.secrets.toml");

if (Number.parseInt(process.versions.node.split(".")[0], 10) < 24) {
  console.error(`Node.js 24 or newer is required (found ${process.versions.node}).`);
  process.exit(1);
}

const panelPassword = randomBytes(18).toString("base64url");
const sessionSecret = randomBytes(32).toString("hex");
const rconPassword = randomBytes(24).toString("base64url");
const adminPassword = randomBytes(18).toString("base64url");
const contents = `# Generated by npm run setup. Keep this file private.

[web]
password = "${panelPassword}"
session_secret = "${sessionSecret}"

[server]
admin_password = "${adminPassword}"
rcon_password = "${rconPassword}"

[steam]
password = ""
`;

await mkdir(configDir, { recursive: true });

let file;
try {
  file = await open(secretsPath, "wx", 0o600);
  await file.writeFile(contents, "utf8");
} catch (error) {
  if (error?.code === "EEXIST") {
    console.error(`Setup stopped: ${secretsPath} already exists.`);
    console.error("Move or remove it first if you intentionally want new credentials.");
    process.exit(1);
  }
  throw error;
} finally {
  await file?.close();
}

// chmod is effective on Unix and harmless on Windows.
await chmod(secretsPath, 0o600);

console.log("First-run configuration created successfully.");
console.log("Panel URL after startup: http://127.0.0.1:8080");
console.log("Username: admin");
console.log(`Password: ${panelPassword}`);
console.log(`Zomboid admin password: ${adminPassword}`);
console.log("Save this password now; it is not printed again.");
